In [1]:
import pandas as pds
import matplotlib.pyplot as plt
import numpy as np
import math
import copy

On commence d'abord par importer nos données :

In [2]:
datatxt=pds.read_csv('data_tp1_app.txt',sep=" ",header=None)
data_entry_raw=open("data_tp1_app.txt","r").read().splitlines()
data_entry=[i.split(" ") for i in data_entry_raw]

On affiche nos données :

In [3]:
#pd.set_option('display.max_row', None)
datatxt

     0         1         2
0    1 -6.315382  6.344938
1    1 -4.943573  7.821684
2    1 -8.920876  2.705258
3    1 -5.661533  7.425065
4    1 -5.918269  5.697313
..  ..       ...       ...
495  5 -1.446325 -0.422072
496  5  0.261599  0.479059
497  5 -2.243814 -0.673345
498  5 -0.489892  0.282347
499  5  0.310185  0.024044

[500 rows x 3 columns]

on donne une structure classe,x,y à notre jeux de données :

In [4]:
df=pds.DataFrame(np.array(datatxt),columns=["classe","x","y"])
df_entry=pds.DataFrame(data_entry,columns=["classe","x","y"])

In [5]:
df

     classe         x         y
0       1.0 -6.315382  6.344938
1       1.0 -4.943573  7.821684
2       1.0 -8.920876  2.705258
3       1.0 -5.661533  7.425065
4       1.0 -5.918269  5.697313
..      ...       ...       ...
495     5.0 -1.446325 -0.422072
496     5.0  0.261599  0.479059
497     5.0 -2.243814 -0.673345
498     5.0 -0.489892  0.282347
499     5.0  0.310185  0.024044

[500 rows x 3 columns]

In [6]:
df_entry

    classe          x          y
0        1  -6.315382   6.344938
1        1  -4.943573   7.821684
2        1  -8.920876   2.705258
3        1  -5.661533   7.425065
4        1  -5.918269   5.697313
..     ...        ...        ...
495      5  -1.446325  -0.422072
496      5   0.261599   0.479059
497      5  -2.243814  -0.673345
498      5  -0.489892   0.282347
499      5   0.310185   0.024044

[500 rows x 3 columns]

On utilise la fonction describe de python pour obtenir des indicateurs statistiques sur notre jeux de données, tout juste avant de le faire de nous même :

In [7]:
df.describe()

          classe           x           y
count  500.00000  500.000000  500.000000
mean     3.00000   -0.092595    0.095844
std      1.41563    5.528565    5.657946
min      1.00000  -10.011338  -12.704430
25%      2.00000   -5.589494   -5.480849
50%      3.00000   -0.088660    0.246180
75%      4.00000    5.149024    5.619648
max      5.00000   10.131971   11.128433

In [8]:
df_entry.describe()

       classe          x         y
count     500        500       500
unique      5        500       500
top         5  -5.377353  3.100940
freq      100          1         1

### Trouvons le centre des classes :

Pour trouver le centre de classe, il nous faut trouver la moyenne de chaque classe par rapport à x et y.

On commence par grouper chaque points dans sa classe, ici une classe est un tableau numpy :

1) on récupère le nombre maximal de classe :

In [9]:
def classesnbr2(data):
    return int(max([ligne[0] for ligne in data]))

In [10]:
def classesnbr(data):
    dfmaxclass=pds.DataFrame(data.sort_values(by=["classe"], ascending=False))
    maxi=int(dfmaxclass["classe"][0:1])
    return maxi

2) on calcul la moyenne de chaque classe

In [11]:
def moyenneclass_op(data):
    dfmeans=pds.DataFrame(data.sort_values(by=["Classe"], ascending=False,columns=["x","y"]))
    nbr_element=[]
    tot=[0,0,0,0,0]
    for i in range(classesnbr2(df_entry)):
        switcher = {
            df_entry['Classe'][0:i]==1: 
            nbr_element[0]=nbr_element[0]+1
            tot[1]=tot[1]+df_entry["x"][0:i]
          ,
            df_entry['Classe'][0:i]==2: 
            nbr_element[2]=nbr_element[2]+1
            tot[2]=tot[2]+df_entry["x"][0:i]
            ,
            df_entry['Classe'][0:i]==3: 
            nbr_element[3]=nbr_element[3]+1
            tot[3]=tot[3]+df_entry["x"][0:i]
            ,
            df_entry['Classe'][0:i]==4: 
            nbr_element[4]=nbr_element[4]+1
            tot[4]=tot[4]+df_entry["x"][0:i]
            ,
            df_entry['Classe'][0:i]==5:
            nbr_element[5]=nbr_element[5]+1
            tot[5]=tot[5]+df_entry["x"][0:i]
            ,
        }
    print switcher.get(argument, "Invalid month")
    array = [ligne[] for ligne in data if (ligne[0])==int(classe)]
    return

SyntaxError: invalid syntax (<ipython-input-11-9db8641580ed>, line 8)

In [12]:
def moyenne(data):
    dfclass=pds.DataFrame(data,columns=["classe"])
    print(dfclass)
    dfX=pds.DataFrame(data.sort_values(by=["classe"], ascending=True),columns=["x"])
    print(dfX)
    dfY=pds.DataFrame(data.sort_values(by=["classe"], ascending=True),columns=["y"])
    print(dfY)

In [13]:
print(df_entry["classe"][0:3])
print(df["x"][0:3])

moyenne(df)

0    1
1    1
2    1
Name: classe, dtype: object
0   -6.315382
1   -4.943573
2   -8.920876
Name: x, dtype: float64
     classe
0       1.0
1       1.0
2       1.0
3       1.0
4       1.0
..      ...
495     5.0
496     5.0
497     5.0
498     5.0
499     5.0

[500 rows x 1 columns]
            x
0   -6.315382
72  -7.452667
71  -3.928538
70  -8.151742
69  -4.275267
..        ...
427  0.858149
426  0.136225
425 -0.563265
435 -0.663033
499  0.310185

[500 rows x 1 columns]
            y
0    6.344938
72   7.347806
71   8.602920
70   3.442773
69   5.778782
..        ...
427 -2.240126
426  0.850784
425 -0.538075
435 -1.906060
499  0.024044

[500 rows x 1 columns]

In [14]:
def classmean(data,classe,axis):
    array = [float(ligne[axis+1]) for ligne in data if str(ligne[0])==int(classe)]
    #array = []
    total = sum(array)
    return (total/len(array)) if len(array) !=0 else 0

3) on récupère la moyenne de chaque classe :

In [15]:
def mean_of_classes(data):
    means=[] #a vector
    for classe in range(classesnbr(data)): 
        means.append([])       
        for i in range(2):
            means[classe].append(classmean(data,classe+1,i))
    return means

In [16]:
means=mean_of_classes(df_entry)
print(means)

[[0, 0], [0, 0], [0, 0], [0, 0], [0, 0]]

In [17]:
print("les moyennes de classes sont : ")
pds.DataFrame(means, index=range(1,len(means)+1),columns=["µx","µy"])

les moyennes de classes sont :

   µx  µy
1   0   0
2   0   0
3   0   0
4   0   0
5   0   0

Mainteanant nous pouvons importer nos données sur lesquelles nous devons porter des décisions :

In [18]:
data_test_raw = open("data_tp1_dec.txt","r").read().splitlines()
data_test = [i.split(" ") for i in data_test_raw]

In [19]:
df2 = pds.DataFrame(data_test,columns=['classe',"x","y"])

In [20]:
df2

    classe          x          y
0        1  -4.840798   5.117552
1        1  -2.458894   5.701029
2        1  -5.195775   6.207984
3        1  -6.059512   4.324269
4        1  -5.864124   8.061702
..     ...        ...        ...
495      5  -0.532394  -0.478236
496      5  -0.596780  -1.310213
497      5   0.645414   0.058871
498      5   0.679295  -1.391780
499      5   0.998671   1.712854

[500 rows x 3 columns]

### Calcul de la distance eucleudienne par interpolation :

In [399]:
def distance_eucl(x1,y1,x2,y2):
    return math.sqrt((x2-x1)**2 + (y2-y1)**2)

In [400]:
def interpolation_eucl(means,data):
    liste_interp=copy.deepcopy(data)
    
    for ligne in range(len(liste_interp)):
        #voici nos 2 nouvelles colonnes du tableau
        liste_interp[ligne].append(-1)
        liste_interp[ligne].append(-1)
        #
        x1=float(liste_interp[ligne][0+1])#le x de chaque ligne
        y1=float(liste_interp[ligne][1+1])#le y de chaque ligne
        #
        for classe in range(0,len(means)):
            x2=float(means[classe][0])
            y2=float(means[classe][1])
            #
            if distance_eucl(x1,y1,x2,y2)<liste_interp[ligne][3] or liste_interp[ligne][3]==-1:
                liste_interp[ligne][3]=distance_eucl(x1,y1,x2,y2)
                liste_interp[ligne][4]=classe+1
        return liste_interp

In [401]:
liste_interpolee = interpolation_eucl(means,data_test)

In [407]:
newdf=pds.DataFrame(liste_interpolee,columns=["classe","x","y","distance","Interpolation"])
newdf

    classe          x          y  distance  Interpolation
0        1  -4.840798   5.117552  7.044336            1.0
1        1  -2.458894   5.701029       NaN            NaN
2        1  -5.195775   6.207984       NaN            NaN
3        1  -6.059512   4.324269       NaN            NaN
4        1  -5.864124   8.061702       NaN            NaN
..     ...        ...        ...       ...            ...
495      5  -0.532394  -0.478236       NaN            NaN
496      5  -0.596780  -1.310213       NaN            NaN
497      5   0.645414   0.058871       NaN            NaN
498      5   0.679295  -1.391780       NaN            NaN
499      5   0.998671   1.712854       NaN            NaN

[500 rows x 5 columns]

#### Déterminons TOP1 & TOP2

In [414]:
topp1=pds.DataFrame(newdf[newdf.classe!=newdf.Interpolation])
topp1

    classe          x          y  distance  Interpolation
0        1  -4.840798   5.117552  7.044336            1.0
1        1  -2.458894   5.701029       NaN            NaN
2        1  -5.195775   6.207984       NaN            NaN
3        1  -6.059512   4.324269       NaN            NaN
4        1  -5.864124   8.061702       NaN            NaN
..     ...        ...        ...       ...            ...
495      5  -0.532394  -0.478236       NaN            NaN
496      5  -0.596780  -1.310213       NaN            NaN
497      5   0.645414   0.058871       NaN            NaN
498      5   0.679295  -1.391780       NaN            NaN
499      5   0.998671   1.712854       NaN            NaN

[500 rows x 5 columns]

In [409]:
TOP1=((500-4)/500)*100
TOP1

99.2

pour trouver TOP2, nous devons regarder la deuxième distance la plus proche parce que le tableau précédent c'est le point X, Y dans leur classe respective, maintenat on peut tester avec une autre classe.

### Trouvons la matrice de confusion

In [422]:
Df_confusionarray=pds.DataFrame(topp1,columns=["classe","1","2","3","4","5"])
#pds.set_option('display.max_row', None)

In [442]:
def moyenneclass_op(data):
    #dfmeans=pds.DataFrame(data.sort_values(by=["Classe"], ascending=False,columns=["x","y"]))
    nbr_element=[]
    tot=[]
    tot.append([])
    switcher = {
        df_entry['classe'][0:99]==1: 
        tot[0].append(tot[0]+1)
        ,
        df_entry['classe'][100:199]==2: 
        tot[1].append(tot[1]+1)
        ,
        df_entry['classe'][200:299]==3: 
        tot[2].append(tot[2]+1)
        ,
        df_entry['classe'][300:399]==4: 
        tot[3].append(tot[3]+1)
        ,
        df_entry['classe'][400:499]==5:
        tot[4].append(tot[4]+1)
    }
    print(switcher.get(data, "Invalid month"))

In [445]:
moyenneclass_op(df_entry)

TypeError: can only concatenate list (not "int") to list

In [428]:
Df_confusionarray

    classe   1   2   3   4   5
0        1 NaN NaN NaN NaN NaN
1        1 NaN NaN NaN NaN NaN
2        1 NaN NaN NaN NaN NaN
3        1 NaN NaN NaN NaN NaN
4        1 NaN NaN NaN NaN NaN
5        1 NaN NaN NaN NaN NaN
6        1 NaN NaN NaN NaN NaN
7        1 NaN NaN NaN NaN NaN
8        1 NaN NaN NaN NaN NaN
9        1 NaN NaN NaN NaN NaN
10       1 NaN NaN NaN NaN NaN
11       1 NaN NaN NaN NaN NaN
12       1 NaN NaN NaN NaN NaN
13       1 NaN NaN NaN NaN NaN
14       1 NaN NaN NaN NaN NaN
15       1 NaN NaN NaN NaN NaN
16       1 NaN NaN NaN NaN NaN
17       1 NaN NaN NaN NaN NaN
18       1 NaN NaN NaN NaN NaN
19       1 NaN NaN NaN NaN NaN
20       1 NaN NaN NaN NaN NaN
21       1 NaN NaN NaN NaN NaN
22       1 NaN NaN NaN NaN NaN
23       1 NaN NaN NaN NaN NaN
24       1 NaN NaN NaN NaN NaN
25       1 NaN NaN NaN NaN NaN
26       1 NaN NaN NaN NaN NaN
27       1 NaN NaN NaN NaN NaN
28       1 NaN NaN NaN NaN NaN
29       1 NaN NaN NaN NaN NaN
30       1 NaN NaN NaN NaN NaN
31       1 NaN NaN NaN NaN NaN
32       1 NaN NaN NaN NaN NaN
33       1 NaN NaN NaN NaN NaN
34       1 NaN NaN NaN NaN NaN
35       1 NaN NaN NaN NaN NaN
36       1 NaN NaN NaN NaN NaN
37       1 NaN NaN NaN NaN NaN
38       1 NaN NaN NaN NaN NaN
39       1 NaN NaN NaN NaN NaN
40       1 NaN NaN NaN NaN NaN
41       1 NaN NaN NaN NaN NaN
42       1 NaN NaN NaN NaN NaN
43       1 NaN NaN NaN NaN NaN
44       1 NaN NaN NaN NaN NaN
45       1 NaN NaN NaN NaN NaN
46       1 NaN NaN NaN NaN NaN
47       1 NaN NaN NaN NaN NaN
48       1 NaN NaN NaN NaN NaN
49       1 NaN NaN NaN NaN NaN
50       1 NaN NaN NaN NaN NaN
51       1 NaN NaN NaN NaN NaN
52       1 NaN NaN NaN NaN NaN
53       1 NaN NaN NaN NaN NaN
54       1 NaN NaN NaN NaN NaN
55       1 NaN NaN NaN NaN NaN
56       1 NaN NaN NaN NaN NaN
57       1 NaN NaN NaN NaN NaN
58       1 NaN NaN NaN NaN NaN
59       1 NaN NaN NaN NaN NaN
60       1 NaN NaN NaN NaN NaN
61       1 NaN NaN NaN NaN NaN
62       1 NaN NaN NaN NaN NaN
63       1 NaN NaN NaN NaN NaN
64       1 NaN NaN NaN NaN NaN
65       1 NaN NaN NaN NaN NaN
66       1 NaN NaN NaN NaN NaN
67       1 NaN NaN NaN NaN NaN
68       1 NaN NaN NaN NaN NaN
69       1 NaN NaN NaN NaN NaN
70       1 NaN NaN NaN NaN NaN
71       1 NaN NaN NaN NaN NaN
72       1 NaN NaN NaN NaN NaN
73       1 NaN NaN NaN NaN NaN
74       1 NaN NaN NaN NaN NaN
75       1 NaN NaN NaN NaN NaN
76       1 NaN NaN NaN NaN NaN
77       1 NaN NaN NaN NaN NaN
78       1 NaN NaN NaN NaN NaN
79       1 NaN NaN NaN NaN NaN
80       1 NaN NaN NaN NaN NaN
81       1 NaN NaN NaN NaN NaN
82       1 NaN NaN NaN NaN NaN
83       1 NaN NaN NaN NaN NaN
84       1 NaN NaN NaN NaN NaN
85       1 NaN NaN NaN NaN NaN
86       1 NaN NaN NaN NaN NaN
87       1 NaN NaN NaN NaN NaN
88       1 NaN NaN NaN NaN NaN
89       1 NaN NaN NaN NaN NaN
90       1 NaN NaN NaN NaN NaN
91       1 NaN NaN NaN NaN NaN
92       1 NaN NaN NaN NaN NaN
93       1 NaN NaN NaN NaN NaN
94       1 NaN NaN NaN NaN NaN
95       1 NaN NaN NaN NaN NaN
96       1 NaN NaN NaN NaN NaN
97       1 NaN NaN NaN NaN NaN
98       1 NaN NaN NaN NaN NaN
99       1 NaN NaN NaN NaN NaN
100      2 NaN NaN NaN NaN NaN
101      2 NaN NaN NaN NaN NaN
102      2 NaN NaN NaN NaN NaN
103      2 NaN NaN NaN NaN NaN
104      2 NaN NaN NaN NaN NaN
105      2 NaN NaN NaN NaN NaN
106      2 NaN NaN NaN NaN NaN
107      2 NaN NaN NaN NaN NaN
108      2 NaN NaN NaN NaN NaN
109      2 NaN NaN NaN NaN NaN
110      2 NaN NaN NaN NaN NaN
111      2 NaN NaN NaN NaN NaN
112      2 NaN NaN NaN NaN NaN
113      2 NaN NaN NaN NaN NaN
114      2 NaN NaN NaN NaN NaN
115      2 NaN NaN NaN NaN NaN
116      2 NaN NaN NaN NaN NaN
117      2 NaN NaN NaN NaN NaN
118      2 NaN NaN NaN NaN NaN
119      2 NaN NaN NaN NaN NaN
120      2 NaN NaN NaN NaN NaN
121      2 NaN NaN NaN NaN NaN
122      2 NaN NaN NaN NaN NaN
123      2 NaN NaN NaN NaN NaN
124      2 NaN NaN NaN NaN NaN
125      2 NaN NaN NaN NaN NaN
126      2 NaN NaN NaN NaN NaN
127      2 NaN NaN NaN NaN NaN
128      2 NaN NaN NaN NaN NaN
129      2 NaN NaN NaN NaN NaN
130      2 NaN NaN NaN NaN NaN
131      2 NaN NaN NaN NaN NaN
132      2 NaN NaN NaN NaN NaN
133      2 NaN NaN NaN NaN NaN
134      2 NaN NaN NaN NaN NaN
135      2 NaN NaN NaN NaN NaN
136      2 NaN NaN NaN NaN NaN
137      2 NaN NaN NaN NaN NaN
138      2 NaN NaN NaN NaN NaN
139      2 NaN NaN NaN NaN NaN
140      2 NaN NaN NaN NaN NaN
141      2 NaN NaN NaN NaN NaN
142      2 NaN NaN NaN NaN NaN
143      2 NaN NaN NaN NaN NaN
144      2 NaN NaN NaN NaN NaN
145      2 NaN NaN NaN NaN NaN
146      2 NaN NaN NaN NaN NaN
147      2 NaN NaN NaN NaN NaN
148      2 NaN NaN NaN NaN NaN
149      2 NaN NaN NaN NaN NaN
150      2 NaN NaN NaN NaN NaN
151      2 NaN NaN NaN NaN NaN
152      2 NaN NaN NaN NaN NaN
153      2 NaN NaN NaN NaN NaN
154      2 NaN NaN NaN NaN NaN
155      2 NaN NaN NaN NaN NaN
156      2 NaN NaN NaN NaN NaN
157      2 NaN NaN NaN NaN NaN
158      2 NaN NaN NaN NaN NaN
159      2 NaN NaN NaN NaN NaN
160      2 NaN NaN NaN NaN NaN
161      2 NaN NaN NaN NaN NaN
162      2 NaN NaN NaN NaN NaN
163      2 NaN NaN NaN NaN NaN
164      2 NaN NaN NaN NaN NaN
165      2 NaN NaN NaN NaN NaN
166      2 NaN NaN NaN NaN NaN
167      2 NaN NaN NaN NaN NaN
168      2 NaN NaN NaN NaN NaN
169      2 NaN NaN NaN NaN NaN
170      2 NaN NaN NaN NaN NaN
171      2 NaN NaN NaN NaN NaN
172      2 NaN NaN NaN NaN NaN
173      2 NaN NaN NaN NaN NaN
174      2 NaN NaN NaN NaN NaN
175      2 NaN NaN NaN NaN NaN
176      2 NaN NaN NaN NaN NaN
177      2 NaN NaN NaN NaN NaN
178      2 NaN NaN NaN NaN NaN
179      2 NaN NaN NaN NaN NaN
180      2 NaN NaN NaN NaN NaN
181      2 NaN NaN NaN NaN NaN
182      2 NaN NaN NaN NaN NaN
183      2 NaN NaN NaN NaN NaN
184      2 NaN NaN NaN NaN NaN
185      2 NaN NaN NaN NaN NaN
186      2 NaN NaN NaN NaN NaN
187      2 NaN NaN NaN NaN NaN
188      2 NaN NaN NaN NaN NaN
189      2 NaN NaN NaN NaN NaN
190      2 NaN NaN NaN NaN NaN
191      2 NaN NaN NaN NaN NaN
192      2 NaN NaN NaN NaN NaN
193      2 NaN NaN NaN NaN NaN
194      2 NaN NaN NaN NaN NaN
195      2 NaN NaN NaN NaN NaN
196      2 NaN NaN NaN NaN NaN
197      2 NaN NaN NaN NaN NaN
198      2 NaN NaN NaN NaN NaN
199      2 NaN NaN NaN NaN NaN
200      3 NaN NaN NaN NaN NaN
201      3 NaN NaN NaN NaN NaN
202      3 NaN NaN NaN NaN NaN
203      3 NaN NaN NaN NaN NaN
204      3 NaN NaN NaN NaN NaN
205      3 NaN NaN NaN NaN NaN
206      3 NaN NaN NaN NaN NaN
207      3 NaN NaN NaN NaN NaN
208      3 NaN NaN NaN NaN NaN
209      3 NaN NaN NaN NaN NaN
210      3 NaN NaN NaN NaN NaN
211      3 NaN NaN NaN NaN NaN
212      3 NaN NaN NaN NaN NaN
213      3 NaN NaN NaN NaN NaN
214      3 NaN NaN NaN NaN NaN
215      3 NaN NaN NaN NaN NaN
216      3 NaN NaN NaN NaN NaN
217      3 NaN NaN NaN NaN NaN
218      3 NaN NaN NaN NaN NaN
219      3 NaN NaN NaN NaN NaN
220      3 NaN NaN NaN NaN NaN
221      3 NaN NaN NaN NaN NaN
222      3 NaN NaN NaN NaN NaN
223      3 NaN NaN NaN NaN NaN
224      3 NaN NaN NaN NaN NaN
225      3 NaN NaN NaN NaN NaN
226      3 NaN NaN NaN NaN NaN
227      3 NaN NaN NaN NaN NaN
228      3 NaN NaN NaN NaN NaN
229      3 NaN NaN NaN NaN NaN
230      3 NaN NaN NaN NaN NaN
231      3 NaN NaN NaN NaN NaN
232      3 NaN NaN NaN NaN NaN
233      3 NaN NaN NaN NaN NaN
234      3 NaN NaN NaN NaN NaN
235      3 NaN NaN NaN NaN NaN
236      3 NaN NaN NaN NaN NaN
237      3 NaN NaN NaN NaN NaN
238      3 NaN NaN NaN NaN NaN
239      3 NaN NaN NaN NaN NaN
240      3 NaN NaN NaN NaN NaN
241      3 NaN NaN NaN NaN NaN
242      3 NaN NaN NaN NaN NaN
243      3 NaN NaN NaN NaN NaN
244      3 NaN NaN NaN NaN NaN
245      3 NaN NaN NaN NaN NaN
246      3 NaN NaN NaN NaN NaN
247      3 NaN NaN NaN NaN NaN
248      3 NaN NaN NaN NaN NaN
249      3 NaN NaN NaN NaN NaN
250      3 NaN NaN NaN NaN NaN
251      3 NaN NaN NaN NaN NaN
252      3 NaN NaN NaN NaN NaN
253      3 NaN NaN NaN NaN NaN
254      3 NaN NaN NaN NaN NaN
255      3 NaN NaN NaN NaN NaN
256      3 NaN NaN NaN NaN NaN
257      3 NaN NaN NaN NaN NaN
258      3 NaN NaN NaN NaN NaN
259      3 NaN NaN NaN NaN NaN
260      3 NaN NaN NaN NaN NaN
261      3 NaN NaN NaN NaN NaN
262      3 NaN NaN NaN NaN NaN
263      3 NaN NaN NaN NaN NaN
264      3 NaN NaN NaN NaN NaN
265      3 NaN NaN NaN NaN NaN
266      3 NaN NaN NaN NaN NaN
267      3 NaN NaN NaN NaN NaN
268      3 NaN NaN NaN NaN NaN
269      3 NaN NaN NaN NaN NaN
270      3 NaN NaN NaN NaN NaN
271      3 NaN NaN NaN NaN NaN
272      3 NaN NaN NaN NaN NaN
273      3 NaN NaN NaN NaN NaN
274      3 NaN NaN NaN NaN NaN
275      3 NaN NaN NaN NaN NaN
276      3 NaN NaN NaN NaN NaN
277      3 NaN NaN NaN NaN NaN
278      3 NaN NaN NaN NaN NaN
279      3 NaN NaN NaN NaN NaN
280      3 NaN NaN NaN NaN NaN
281      3 NaN NaN NaN NaN NaN
282      3 NaN NaN NaN NaN NaN
283      3 NaN NaN NaN NaN NaN
284      3 NaN NaN NaN NaN NaN
285      3 NaN NaN NaN NaN NaN
286      3 NaN NaN NaN NaN NaN
287      3 NaN NaN NaN NaN NaN
288      3 NaN NaN NaN NaN NaN
289      3 NaN NaN NaN NaN NaN
290      3 NaN NaN NaN NaN NaN
291      3 NaN NaN NaN NaN NaN
292      3 NaN NaN NaN NaN NaN
293      3 NaN NaN NaN NaN NaN
294      3 NaN NaN NaN NaN NaN
295      3 NaN NaN NaN NaN NaN
296      3 NaN NaN NaN NaN NaN
297      3 NaN NaN NaN NaN NaN
298      3 NaN NaN NaN NaN NaN
299      3 NaN NaN NaN NaN NaN
300      4 NaN NaN NaN NaN NaN
301      4 NaN NaN NaN NaN NaN
302      4 NaN NaN NaN NaN NaN
303      4 NaN NaN NaN NaN NaN
304      4 NaN NaN NaN NaN NaN
305      4 NaN NaN NaN NaN NaN
306      4 NaN NaN NaN NaN NaN
307      4 NaN NaN NaN NaN NaN
308      4 NaN NaN NaN NaN NaN
309      4 NaN NaN NaN NaN NaN
310      4 NaN NaN NaN NaN NaN
311      4 NaN NaN NaN NaN NaN
312      4 NaN NaN NaN NaN NaN
313      4 NaN NaN NaN NaN NaN
314      4 NaN NaN NaN NaN NaN
315      4 NaN NaN NaN NaN NaN
316      4 NaN NaN NaN NaN NaN
317      4 NaN NaN NaN NaN NaN
318      4 NaN NaN NaN NaN NaN
319      4 NaN NaN NaN NaN NaN
320      4 NaN NaN NaN NaN NaN
321      4 NaN NaN NaN NaN NaN
322      4 NaN NaN NaN NaN NaN
323      4 NaN NaN NaN NaN NaN
324      4 NaN NaN NaN NaN NaN
325      4 NaN NaN NaN NaN NaN
326      4 NaN NaN NaN NaN NaN
327      4 NaN NaN NaN NaN NaN
328      4 NaN NaN NaN NaN NaN
329      4 NaN NaN NaN NaN NaN
330      4 NaN NaN NaN NaN NaN
331      4 NaN NaN NaN NaN NaN
332      4 NaN NaN NaN NaN NaN
333      4 NaN NaN NaN NaN NaN
334      4 NaN NaN NaN NaN NaN
335      4 NaN NaN NaN NaN NaN
336      4 NaN NaN NaN NaN NaN
337      4 NaN NaN NaN NaN NaN
338      4 NaN NaN NaN NaN NaN
339      4 NaN NaN NaN NaN NaN
340      4 NaN NaN NaN NaN NaN
341      4 NaN NaN NaN NaN NaN
342      4 NaN NaN NaN NaN NaN
343      4 NaN NaN NaN NaN NaN
344      4 NaN NaN NaN NaN NaN
345      4 NaN NaN NaN NaN NaN
346      4 NaN NaN NaN NaN NaN
347      4 NaN NaN NaN NaN NaN
348      4 NaN NaN NaN NaN NaN
349      4 NaN NaN NaN NaN NaN
350      4 NaN NaN NaN NaN NaN
351      4 NaN NaN NaN NaN NaN
352      4 NaN NaN NaN NaN NaN
353      4 NaN NaN NaN NaN NaN
354      4 NaN NaN NaN NaN NaN
355      4 NaN NaN NaN NaN NaN
356      4 NaN NaN NaN NaN NaN
357      4 NaN NaN NaN NaN NaN
358      4 NaN NaN NaN NaN NaN
359      4 NaN NaN NaN NaN NaN
360      4 NaN NaN NaN NaN NaN
361      4 NaN NaN NaN NaN NaN
362      4 NaN NaN NaN NaN NaN
363      4 NaN NaN NaN NaN NaN
364      4 NaN NaN NaN NaN NaN
365      4 NaN NaN NaN NaN NaN
366      4 NaN NaN NaN NaN NaN
367      4 NaN NaN NaN NaN NaN
368      4 NaN NaN NaN NaN NaN
369      4 NaN NaN NaN NaN NaN
370      4 NaN NaN NaN NaN NaN
371      4 NaN NaN NaN NaN NaN
372      4 NaN NaN NaN NaN NaN
373      4 NaN NaN NaN NaN NaN
374      4 NaN NaN NaN NaN NaN
375      4 NaN NaN NaN NaN NaN
376      4 NaN NaN NaN NaN NaN
377      4 NaN NaN NaN NaN NaN
378      4 NaN NaN NaN NaN NaN
379      4 NaN NaN NaN NaN NaN
380      4 NaN NaN NaN NaN NaN
381      4 NaN NaN NaN NaN NaN
382      4 NaN NaN NaN NaN NaN
383      4 NaN NaN NaN NaN NaN
384      4 NaN NaN NaN NaN NaN
385      4 NaN NaN NaN NaN NaN
386      4 NaN NaN NaN NaN NaN
387      4 NaN NaN NaN NaN NaN
388      4 NaN NaN NaN NaN NaN
389      4 NaN NaN NaN NaN NaN
390      4 NaN NaN NaN NaN NaN
391      4 NaN NaN NaN NaN NaN
392      4 NaN NaN NaN NaN NaN
393      4 NaN NaN NaN NaN NaN
394      4 NaN NaN NaN NaN NaN
395      4 NaN NaN NaN NaN NaN
396      4 NaN NaN NaN NaN NaN
397      4 NaN NaN NaN NaN NaN
398      4 NaN NaN NaN NaN NaN
399      4 NaN NaN NaN NaN NaN
400      5 NaN NaN NaN NaN NaN
401      5 NaN NaN NaN NaN NaN
402      5 NaN NaN NaN NaN NaN
403      5 NaN NaN NaN NaN NaN
404      5 NaN NaN NaN NaN NaN
405      5 NaN NaN NaN NaN NaN
406      5 NaN NaN NaN NaN NaN
407      5 NaN NaN NaN NaN NaN
408      5 NaN NaN NaN NaN NaN
409      5 NaN NaN NaN NaN NaN
410      5 NaN NaN NaN NaN NaN
411      5 NaN NaN NaN NaN NaN
412      5 NaN NaN NaN NaN NaN
413      5 NaN NaN NaN NaN NaN
414      5 NaN NaN NaN NaN NaN
415      5 NaN NaN NaN NaN NaN
416      5 NaN NaN NaN NaN NaN
417      5 NaN NaN NaN NaN NaN
418      5 NaN NaN NaN NaN NaN
419      5 NaN NaN NaN NaN NaN
420      5 NaN NaN NaN NaN NaN
421      5 NaN NaN NaN NaN NaN
422      5 NaN NaN NaN NaN NaN
423      5 NaN NaN NaN NaN NaN
424      5 NaN NaN NaN NaN NaN
425      5 NaN NaN NaN NaN NaN
426      5 NaN NaN NaN NaN NaN
427      5 NaN NaN NaN NaN NaN
428      5 NaN NaN NaN NaN NaN
429      5 NaN NaN NaN NaN NaN
430      5 NaN NaN NaN NaN NaN
431      5 NaN NaN NaN NaN NaN
432      5 NaN NaN NaN NaN NaN
433      5 NaN NaN NaN NaN NaN
434      5 NaN NaN NaN NaN NaN
435      5 NaN NaN NaN NaN NaN
436      5 NaN NaN NaN NaN NaN
437      5 NaN NaN NaN NaN NaN
438      5 NaN NaN NaN NaN NaN
439      5 NaN NaN NaN NaN NaN
440      5 NaN NaN NaN NaN NaN
441      5 NaN NaN NaN NaN NaN
442      5 NaN NaN NaN NaN NaN
443      5 NaN NaN NaN NaN NaN
444      5 NaN NaN NaN NaN NaN
445      5 NaN NaN NaN NaN NaN
446      5 NaN NaN NaN NaN NaN
447      5 NaN NaN NaN NaN NaN
448      5 NaN NaN NaN NaN NaN
449      5 NaN NaN NaN NaN NaN
450      5 NaN NaN NaN NaN NaN
451      5 NaN NaN NaN NaN NaN
452      5 NaN NaN NaN NaN NaN
453      5 NaN NaN NaN NaN NaN
454      5 NaN NaN NaN NaN NaN
455      5 NaN NaN NaN NaN NaN
456      5 NaN NaN NaN NaN NaN
457      5 NaN NaN NaN NaN NaN
458      5 NaN NaN NaN NaN NaN
459      5 NaN NaN NaN NaN NaN
460      5 NaN NaN NaN NaN NaN
461      5 NaN NaN NaN NaN NaN
462      5 NaN NaN NaN NaN NaN
463      5 NaN NaN NaN NaN NaN
464      5 NaN NaN NaN NaN NaN
465      5 NaN NaN NaN NaN NaN
466      5 NaN NaN NaN NaN NaN
467      5 NaN NaN NaN NaN NaN
468      5 NaN NaN NaN NaN NaN
469      5 NaN NaN NaN NaN NaN
470      5 NaN NaN NaN NaN NaN
471      5 NaN NaN NaN NaN NaN
472      5 NaN NaN NaN NaN NaN
473      5 NaN NaN NaN NaN NaN
474      5 NaN NaN NaN NaN NaN
475      5 NaN NaN NaN NaN NaN
476      5 NaN NaN NaN NaN NaN
477      5 NaN NaN NaN NaN NaN
478      5 NaN NaN NaN NaN NaN
479      5 NaN NaN NaN NaN NaN
480      5 NaN NaN NaN NaN NaN
481      5 NaN NaN NaN NaN NaN
482      5 NaN NaN NaN NaN NaN
483      5 NaN NaN NaN NaN NaN
484      5 NaN NaN NaN NaN NaN
485      5 NaN NaN NaN NaN NaN
486      5 NaN NaN NaN NaN NaN
487      5 NaN NaN NaN NaN NaN
488      5 NaN NaN NaN NaN NaN
489      5 NaN NaN NaN NaN NaN
490      5 NaN NaN NaN NaN NaN
491      5 NaN NaN NaN NaN NaN
492      5 NaN NaN NaN NaN NaN
493      5 NaN NaN NaN NaN NaN
494      5 NaN NaN NaN NaN NaN
495      5 NaN NaN NaN NaN NaN
496      5 NaN NaN NaN NaN NaN
497      5 NaN NaN NaN NaN NaN
498      5 NaN NaN NaN NaN NaN
499      5 NaN NaN NaN NaN NaN